---
title: "STAT 206 Homework 3"
author: "Emilia Avanes"
output:
  word_document: default
  pdf_document: default
---


  
You will estimate the power-law scaling model, and its uncertainty, using the data alluded to in lecture, available in the file `gmp.dat` from lecture, which contains data for 2006.
```{r}
library(dplyr)
library(MASS)
gmp <- read.table("https://faculty.ucr.edu/~jflegal/206/gmp-2013.dat")
gmp$pop <- round(gmp$gmp/gmp$pcgmp)

## 1. First, plot the data as in lecture, with per capita GMP on the y-axis and population on the x-axis. Add the curve function with the default values provided in lecture. Add two more curves corresponding to $a=0.1$ and $a=0.15$; use the `col` option to give each curve a different color (of your choice).

plot(pcgmp~pop, data=gmp, log="x", xlab="Population", ylab="Per-Capita Economic 
     Output ($/person-year)", main="US Metropolitan Areas, 2006")

curve(6611*x^(1/8),add=TRUE,col="blue")
curve(6611*x^(.1),add=TRUE,col="red")
curve(6611*x^(.15),add=TRUE,col="green")

##2. Write a function, called `mse()`, which calculates the mean squared error of the model on a given data set. `mse()` should take three arguments: a numeric vector of length two, the first component standing for y0 and the second for a; a numerical vector containing the values of N; and a numerical vector containing the values of Y.  The function should return a single numerical value. The latter two arguments should have as the default values the columns `pop` and `pcgmp` (respectively) from the `gmp` data frame from lecture.  Your function may not use `for()` or any other loop. Check that, with the default data, you get the following values.


mse <- function(num_vec, N_POP=gmp$pop, Y_GMP=gmp$pcgmp) {
  y0 <- num_vec[1]
  a <- num_vec[2]
  mse <-mean (abs(Y_GMP - (y0*N_POP^a)^2))
  return (mse)
}


mse (c(6611, 0.15))

mse (c(5000, 0.10))


## 3. R has several built-in functions for optimization, which we will meet as we go through the course.  One of the simplest is `nlm()`, or non-linear minimization. `nlm()` takes two required arguments: a function, and a starting value for that function. Run `nlm()` three times with your function `mse()` and three starting value pairs for y0 and a as in:


num_vec=c(y0=6611,a=1/8)
nlm(mse, num_vec)[c("minimum", "estimate")]

num_vec=c(y0=5000,a=.1)
nlm(mse, num_vec)[c("minimum", "estimate")]

num_vec=c(y0=6000,a=.15)
nlm(mse, num_vec)[c("minimum", "estimate")]

## What do the quantities `minimum` and `estimate` represent? What values does it return for these?
## The minimum returns: 41459.4, this represents the minimum of of the MSE funciton given the starting values of y0=6611 and a=1/8.
## The estimate returns the point for y0 and a which the minimum value of the MSE function is obtained. This estimate is dependent on the starting values for the function. However the minimum is the same since it is calculation of a global minimum for the whole function.

## 5.Using `nlm()`, and the `mse()` function you wrote, write a function, `plm()`, which estimates the parameters y0 and a of the model by minimizing the mean squared error.  It should take the following arguments: an initial guess for y0; an initial guess for a; a vector containing the N values; a vector containing the Y values.  All arguments except the initial guesses should have suitable default values.  It should return a list with the following components: the final guess for y0; the final guess for a; the final value of the MSE.  Your function must call those you wrote in earlier questions (it should not repeat their code), and the appropriate arguments to `plm()` should be passed on to them.  

plm <- function(num_vec, N_POP=gmp$pop, Y_GMP=gmp$pcgmp) {
  nlm_last <- nlm (mse, num_vec, N=N_POP, Y=Y_GMP)
  y0_last <- nlm_last [['estimate']][1]
  a_last <- nlm_last [['estimate']][2]
  mse_last <-nlm_last[['minimum']]
  
  return (c(y0_last, a_last, mse_last))
}

num_vec = c(6611, 0.15)
plm(c(num_vec))

num_vec = c(5000, 0.10)
plm(c(num_vec))

## The values for PLM function are not the same for the two different estimates. The y0=5000 and a=.10 estimate has the lower MSE.


## 7. Convince yourself the jackknife can work.
## 7a. Calculate the mean per-capita GMP across cities, and the standard error of this mean, using the built-in functions `mean()` and `sd()`, and the formula for the standard error of the mean you learned in your intro. stats. class (or looked up on Wikipedia...).

mean_GMP = mean (gmp$pcgmp)
sd_GMP = sd (gmp$pcgmp)
std_error_mean = (sd_GMP/381)
print (std_error_mean)

## 7b. Write a function which takes in an integer `i`, and calculate the mean per-capita GMP for every city _except_ city number `i`.

 
mpc_GMP <-function (i){
  newgmp<- gmp[-c(i),]
  newmean_GMP <- mean (newgmp$pcgmp)
  print (mean (newgmp$pcgmp))
}

```
7c. Using this function, create a vector, `jackknifed.means`, which has the mean per-capita GMP where every city is held out in turn.  (You may use a `for` loop or `sapply()`.)


7d. Using the vector `jackknifed.means`, calculate the jack-knife approximation to the standard error of the mean.  How well does it match your answer from part (a)?

8. Write a function, `plm.jackknife()`, to calculate jackknife standard errors for the parameters $y_0$ and $a$.  It should take the same arguments as `plm()`, and return standard errors for both parameters.  This function should call your `plm()` function repeatedly.  What standard errors do you get for the two parameters?

9. The file `gmp-2013.dat` contains measurements for for 2013.  Load it, and use `plm()` and `plm.jackknife` to estimate the parameters of the model for 2013, and their standard errors.  Have the parameters of the model changed significantly?
